version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: jodelclone_Db_container
    environment:
      - MONGO_INITDB_DATABASE=jodelclone_DB
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./database/db:/data/db
    restart: unless-stopped

    
  